[pytest]
filterwarnings =
    ignore:The anyio.abc.BlockingPortal alias is deprecated.*:DeprecationWarning:starlette.testclient
    ignore:'asyncio.iscoroutinefunction' is deprecated and slated for removal in Python 3.16.*:DeprecationWarning:chromadb.telemetry.opentelemetry
    ignore:'asyncio.iscoroutinefunction' is deprecated and slated for removal in Python 3.16.*:DeprecationWarning:slowapi.extension