[pytest]
filterwarnings =
    ignore::DeprecationWarning:chromadb.telemetry.opentelemetry
    ignore:.*anyio.abc.BlockingPortal.*:DeprecationWarning
    ignore:.*httpx with starlette.testclient.*:
    ignore::DeprecationWarning:slowapi.extension