"""
Response schemas for the AgentIQ API.

Keeping response shapes explicit (rather than returning raw internal
state) means we control exactly what the frontend sees and never leak
internal implementation details.
"""

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field

from app.graph.state import AgentEvent, Critique, DraftReport, Evidence, Task


class ResearchStartedResponse(BaseModel):
    """Response returned when a research session is started."""

    research_id: str = Field(
        ...,
        description="Unique identifier of the research session.",
        examples=["550e8400-e29b-41d4-a716-446655440000"],
    )

    status: str = Field(
        ...,
        description="Current research session status.",
        examples=["running"],
    )


class ResearchStatusResponse(BaseModel):
    """Response containing the current state of a research session."""

    research_id: str = Field(
        ...,
        description="Unique identifier of the research session.",
        examples=["550e8400-e29b-41d4-a716-446655440000"],
    )

    status: str = Field(
        ...,
        description="Current status of the research session.",
        examples=["running", "completed", "failed"],
    )

    user_goal: str = Field(
        ...,
        description="Original research goal submitted by the user.",
        examples=["Impact of generative AI on developer productivity"],
    )

    tasks: list[Task] = Field(
        default_factory=list,
        description="Research tasks generated by the planner.",
    )

    evidence: list[Evidence] = Field(
        default_factory=list,
        description="Evidence collected during research.",
    )

    evidence_count: int = Field(
        default=0,
        description="Number of evidence items collected.",
    )

    revision_count: int = Field(
        default=0,
        description="Number of report revisions performed.",
    )

    final_report: Optional[DraftReport] = Field(
        default=None,
        description="Final generated research report, when available.",
    )

    critique: Optional[Critique] = Field(
        default=None,
        description="Critique generated during report evaluation.",
    )

    errors: list[str] = Field(
        default_factory=list,
        description="Errors encountered during the research pipeline.",
    )

    images: list[dict] = Field(
        default_factory=list,
        description="Images collected during research.",
    )

    videos: list[dict] = Field(
        default_factory=list,
        description="Videos collected during research.",
    )
class ResearchEventsResponse(BaseModel):
    """Response containing agent progress events for a research session."""

    research_id: str = Field(
        ...,
        description="Unique identifier of the research session.",
        examples=["550e8400-e29b-41d4-a716-446655440000"],
    )

    events: list[AgentEvent] = Field(
        default_factory=list,
        description="Agent events emitted during the research pipeline.",
    )

class DocumentUploadResponse(BaseModel):
    """Response returned after a document is uploaded."""

    filename: str = Field(
        ...,
        description="Name of the uploaded document.",
        examples=["research-paper.pdf"],
    )

    chunks_added: int = Field(
        ...,
        description="Number of document chunks added to the knowledge base.",
        examples=[42],
    )

    status: str = Field(
        ...,
        description="Upload processing status.",
        examples=["success"],
    )

class HealthResponse(BaseModel):
    """Response returned by the API health check."""

    status: str = Field(
        ...,
        description="Current health status of the AgentIQ API.",
        examples=["ok"],
    )

class ResearchHistoryItem(BaseModel):
    """A lightweight entry in the research history list."""

    research_id: str = Field(
        ...,
        description="Unique identifier of the research session.",
        examples=["550e8400-e29b-41d4-a716-446655440000"],
    )

    user_goal: str = Field(
        ...,
        description="Research goal submitted by the user.",
        examples=["Impact of generative AI on developer productivity"],
    )

    status: str = Field(
        ...,
        description="Current status of the research session.",
        examples=["completed"],
    )

    created_at: Optional[str] = Field(
        default=None,
        description="ISO 8601 timestamp when the research session was created.",
        examples=["2026-09-18T12:30:00"],
    )

    final_report_title: Optional[str] = Field(
        default=None,
        description="Title of the final report, when available.",
        examples=["Impact of Generative AI on Developer Productivity"],
    )


class ResearchHistoryResponse(BaseModel):
    """Response containing lightweight research history entries."""

    sessions: list[ResearchHistoryItem] = Field(
        default_factory=list,
        description="Recent research sessions, newest first.",
    )

class ResearchHistoryResponse(BaseModel):
    """Response for GET /api/research (list)"""
    sessions: list[ResearchHistoryItem] = Field(default_factory=list)